// <auto-generated />
using System;
using AspnetCoreSearchTerm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspnetCoreSearchTerm.Migrations
{
    [DbContext(typeof(AspnetCoreSearchTermContext))]
    partial class AspnetCoreSearchTermContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspnetCoreSearchTerm.Models.SearchTerm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PageSearchEnter");

                    b.Property<int>("SearchBarFieldType");

                    b.Property<string>("SearchByUser");

                    b.Property<DateTime>("SearchDateTime");

                    b.Property<string>("SearchKeyword");

                    b.Property<int?>("SearchSequence");

                    b.HasKey("ID");

                    b.ToTable("SearchTerm");
                });
#pragma warning restore 612, 618
        }
    }
}
